### ISSUE TITLE
Taps not accurate

### ISSUE THREAD

**Issue by Nixo371** [Nixo371/egg.nucieda.com#14]
Code checks if a random number is smaller than an egg's rarity. But when the number is smaller than 1/500, it's also smaller than 1/250, which removes half of our expected 1/250 eggs.

**Comment by acoursey3** [comment]
Resolved by adding independent RNG checks for each rarity. We will need to revisit this because the max roll is set to 100k or 1m for now. It may not be accurate when using sauce above those amounts. We need to find a way to only display the rarities that will be accurate
